---
- name: Get Jove Spark
  command: curl -o jove-spark.tar.gz  https://oss.sonatype.org/content/repositories/snapshots/sh/jove/jove-spark-cli_1.3_2.11/0.1.1-1-SNAPSHOT/jove-spark-cli_1.3_2.11-0.1.1-1-SNAPSHOT.tar.gz
  tags:
    -jove-spark

- name: Make Jove spark dir
  shell: rm -rf /usr/local/jove-spark
  tags:
    -jove-spark

- name: Unpack tar
  command: /bin/tar -xzf jove-spark.tar.gz -C /usr/local/jove-spark --strip-components=1 creates=/usr/local/jove-spark
  tags:
    -jove-spark

- name: Install Jove Spark kernel
  shell: chdir=/usr/local/jove-spark/bin ./jove-spark-1.3 --kernel-spec
  sudo: no
  tags:
    -jove-spark
