alias ll='ls -alF'
alias la='ls -A'
alias l='ls -1 --group-directories-first'

alias j='jump'


# Add an "alert" alias for long running commands. Use like so:
# sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# start ipython notebook server
alias start_ipynb_server="screen -S ipython_notebook -dm bash -c 'ipython notebook --profile dsb'"

# stop ipython notebook server
alias stop_ipynb_server="screen -ls ipython_notebook | grep Detached | cut -d. -f1 | awk '{print $1}' | xargs kill"

# kill all screens
alias screen_killall="screen -ls | grep Detached | cut -d. -f1 | awk '{print $1}' | xargs kill"
