---
- name: Update cache
  apt: update_cache=yes
  tags:
    - deploy

- name: Add Docker repository key
  command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
  tags:
    - deploy

- name: Add Docker repository to APT
  shell: echo deb https://get.docker.com/ubuntu docker main > /etc/apt/sources.list.d/docker.list
  tags:
    - deploy

- name: Update cache
  apt: update_cache=true 
  tags:
    - deploy

- name: Install Docker 
  apt: pkg=lxc-docker state=present
  tags:
    - deploy
