#!/bin/sh

echo " * Data Science Box:                 https://github.com/equialgo/data-science-box"
echo " * Data Science at the Command Line: http://datascienceatthecommandline.com"
echo " * Data Science at the Command Line: http://datascienceatthecommandline.com"
echo " * Data Science Toolbox:             http://datasciencetoolbox.org"
echo " * Ubuntu documentation:             http://help.ubuntu.com"
