---
- name: Install python apt packages 
  apt: pkg={{item}} state=latest
  with_items: apt_packages
  tags: 
    - python-packages

- name: Easy_install pip
  easy_install: name=pip
  tags: 
    - python

- name: Install Python packages
  pip: name={{item}} state=latest
  with_items: pip_packages
  tags:
    - python-packages

- name: Install llvlite for numba
  shell: sudo sh -c "LLVM_CONFIG=/usr/bin/llvm-config-3.6 pip install llvmlite"
  tags: 
    - python-packages

- name: Getting Numba repo
  git: repo=https://github.com/numba/numba.git dest=/tmp/numba/
  tags:
    - python-packages

- name: Install Numba
  shell: chdir=/tmp/numba/ pip install -r requirements.txt; python setup.py build_ext --inplace; python setup.py install
  tags:
    - python-packages

- name: Install mysql-connector-python
  pip: name=mysql-connector-python state=latest extra_args='--allow-external mysql-connector-python'
  tags:
    - python-packages

- name: Getting RISE repo
  git: repo=https://github.com/damianavila/RISE.git dest=/tmp/rise/
  tags:
    - python-packages

- name: Install RISE
  shell: chdir=/tmp/rise/ python setup.py install
  tags:
    - python-packages  
