---
- name: Install python apt packages 
  apt: pkg={{item}} state=latest
  with_items: apt_packages
  tags: 
    - python-packages

- name: Easy_install pip
  easy_install: name=pip
  tags: 
    - python

- name: Install Python packages
  pip: name={{item}} state=latest
  with_items: pip_packages
  tags:
    - python-packages

- name: Install llvlite for numba
  shell: sudo sh -c "LLVM_CONFIG=/usr/bin/llvm-config-3.5 pip install llvmlite"
  tags: 
    - python-packages

- name: Getting Numba repo
  git: repo=https://github.com/numba/numba.git dest=/tmp/numba/
  tags:
    - python-packages

- name: Install Numba
  shell: chdir=/tmp/numba/ pip install -r requirements.txt; python setup.py build_ext --inplace; python setup.py install
  tags:
    - python-packages
