---
- name: Add repository for node.js
  apt_repository: repo='ppa:chris-lea/node.js' update-cache=yes
  tags:
    - nodejs

- name: Install nodejs package
  apt: pkg=nodejs state=latest
  tags:
    - nodejs


