---
- hosts: all
  sudo: yes
  vars:
    parallel_version: 20140622
  tasks:
    - name: Make sure that the repos directory exists
      file: path=/home/vagrant/repos state=directory owner=vagrant group=vagrant
    - name: Make sure that the .bin directory exists
      file: path=/home/vagrant/.bin state=directory owner=vagrant group=vagrant

    - name: Add repository for node.js
      apt_repository: repo='ppa:chris-lea/node.js' update-cache=yes

    - name: Configure Go
      shell: echo 'golang-go golang-go/dashboard boolean true' > /tmp/preseed.conf
    - shell: debconf-set-selections /tmp/preseed.conf

    - name: Install Ubuntu packages
      apt: pkg={{item}} state=latest
      with_items:
        - git
        - python-pycurl
        - python-dev
        - libxml2-dev # lxml
        - libxslt1-dev # lxml
        - zlib1g-dev # lxml
        - libfreetype6-dev # for matplotlib
        - python-numpy # scipy stack
        - python-scipy # scipy stack
        - python-scikits-learn # scipy stack
        - python-matplotlib # scipy stack
        - ipython # scipy stack
        - ipython-notebook # scipy stack
        - python-pandas # scipy stack
        - python-sympy # scipy stack
        - python-nose # scipy stack
        - python-statsmodels # scipy stack
        - tree
        - imagemagick # display
        - feedgnuplot
        - bc
        - libeigen3-dev #tapkee
        - libarpack2-dev # tapkee
        - cmake # tapkee
        - golang-go
        - nodejs
        - make
        - curl
        - g++
        - python-software-properties 
        - python-setuptools
        - p7zip-full
        - unrar-free
        - unzip
        - openjdk-6-jdk
        - leiningen
        - cowsay
        - screen

    - name: Get Data Science at the Command Line tools, data, and scripts
      git: repo=https://github.com/jeroenjanssens/data-science-at-the-command-line.git dest=/home/vagrant/.data-science-at-the-command-line 
    - name: Create symlink for book directory
      shell: ln -s /home/vagrant/.data-science-at-the-command-line/book /home/vagrant/book

    - shell: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
    - apt_repository: repo='deb http://cran.rstudio.com/bin/linux/ubuntu trusty/' state=present
    - apt: pkg=r-base-dev state=latest update_cache=yes
    - name: Install R packages
      shell: echo "install.packages(c('{{item}}'),repos='http://cran.us.r-project.org')" | R --slave --no-save --no-restore-history
      with_items:
        - ggplot2
        - sqldf
        - dplyr

    - name: Install jq
      get_url: url=http://stedolan.github.io/jq/download/linux64/jq dest=/home/vagrant/.bin/jq mode=0755 owner=vagrant group=vagrant

    - name: Install json2csv
      shell: sudo GOPATH=/home/vagrant/.go go get github.com/jehiah/json2csv

    - name: Get npm
      get_url: url=http://npmjs.org/install.sh dest=/tmp/install.sh
    - name: Install npm
      shell: sudo clean=yes sh /tmp/install.sh

    - name: Install xml2json
      npm: name=xml2json-command global=yes

    - name: Easy_install pip (apt-get gives error)
      easy_install: name=pip

    - name: Install Python packages
      pip: name={{item}} state=latest
      with_items:
        - awscli
        - csvkit
        - bigmler
        - cssselect
        - lxml
        - joblib
        - six
        - PrettyTable
        - beautifulsoup4
        - configparser
        - futures
        - logutils
        - ggplot
        - seaborn
        - paramiko

    - name: Download GNU Parallel
      get_url: url=http://ftp.gnu.org/gnu/parallel/parallel-{{ parallel_version }}.tar.bz2 dest=/home/vagrant/parallel-{{ parallel_version }}.tar.bz2
    - name: Install GNU Parallel
      shell: | 
        tar -xvjf /home/vagrant/parallel-{{ parallel_version }}.tar.bz2
        rm parallel-{{ parallel_version }}.tar.bz2
        cd parallel-{{ parallel_version }}
        ./configure && make && make install
        cd ..
        rm -rf parallel-{{ parallel_version }}
      args:
        chdir: /home/vagrant/

    - name: Install SKLL
      pip: name=skll state=latest extra_args=--no-deps

    #- name: Get Drake
    #  git: repo=https://github.com/Factual/drake.git dest=/home/vagrant/repos/drake/
    #  sudo: no # lein does not work with sudo
    #- name: Compile Drake
    #  shell: chdir=/home/vagrant/repos/drake  /usr/bin/lein uberjar
    #  sudo: no
    - name: Move Drake
      shell: mv /vagrant/provisioning/drake/drake.jar /home/vagrant/.bin/
    
    - name: Get Drip
      git: repo=https://github.com/flatland/drip.git dest=/home/vagrant/.drip-repo
    - name: Install Drip
      shell: chdir=/home/vagrant/.drip-repo make prefix=/home/vagrant/.bin/ install

    - name: Download csvfix
      get_url: url=https://bitbucket.org/neilb/csvfix/get/version-1.6.zip dest=/tmp/csvfix.zip
    - name: Unpack csvfix
      shell: chdir=/tmp/ unzip csvfix.zip; mv neilb* csvfix
    - name: Install csvfix
      shell: chdir=/tmp/csvfix make lin
    - name: Move csvfix
      shell: mv /tmp/csvfix/csvfix/bin/csvfix /home/vagrant/.bin/

    - name: Get Weka
      get_url: url=http://downloads.sourceforge.net/project/weka/weka-3-7/3.7.11/weka-3-7-11.zip dest=/home/vagrant/repos/weka.zip
    - name: Install Weka
      shell: |
        unzip weka.zip
        mv weka-3-7-11/weka.jar /home/vagrant/.bin/weka.jar
      args:
        chdir: /home/vagrant/repos

    #- name: Get Tapkee
      #git: repo=https://github.com/lisitsyn/tapkee.git dest=/home/vagrant/repos/tapkee/
    #- file: path=/home/vagrant/repos/tapkee/build state=directory 
    #- shell: cmake .. && make
      #args:
        #chdir: /home/vagrant/repos/tapkee/build
    #- name: Move Tapkee
      #shell: mv /home/vagrant/repos/tapkee/bin/tapkee /home/vagrant/.bin/

    - name: Clone csvquote
      git: repo=https://github.com/dbro/csvquote.git dest=/home/vagrant/repos/csvquote/
    - name: Install csvquote
      shell: chdir=/home/vagrant/repos/csvquote make; make install

    - name: Get mysql-connector-python
      get_url: url=http://dev.mysql.com/get/Downloads/Connector-Python/mysql-connector-python-1.2.3.zip dest=/home/vagrant/repos/mysql-connector-python-1.2.3.zip
    - name: Unzip mysql-connector-python
      shell: chdir=/home/vagrant/repos unzip mysql-connector-python-1.2.3.zip
    - name: Install mysql-connector-python
      shell: chdir=/home/vagrant/repos/mysql-connector-python-1.2.3 python setup.py install

    - name: Delete repos directory
      shell: rm -rf /home/vagrant/repos

    - name: Create symlink for dotfiles
      shell: ln -sf /vagrant/provisioning/dotfiles/{{ item }} /home/vagrant/.{{ item }}
      with_items:
        - bash_aliases
        - bash_completion
        - bashrc
        - profile

    - name: Create symlink for MOTD
      shell: ln -sf /vagrant/provisioning/motd/{{ item }} /etc/update-motd.d/{{ item }}
      with_items:
        - 00-header
        - 10-help-text

    - name: Update MOTD
      shell: run-parts /etc/update-motd.d/ | tee /var/run/motd.dynamic

    - name: Change owner
      file: path=/home/vagrant state=directory owner=vagrant group=vagrant recurse=yes

    - name: Create workspace
      file: path=/vagrant/workspace state=directory owner=vagrant group=vagrant
    - name: Linking workspace  
      shell: ln -s /vagrant/workspace /home/vagrant/workspace
      
    - name: creating dsb ipython profile
      shell: /usr/bin/ipython profile create dsb
      sudo: no
    - name: updating ipython configuration
      template: src=templates/ipython_notebook_config.py.j2 dest=/home/vagrant/.ipython/profile_dsb/ipython_notebook_config.py owner=vagrant group=vagrant mode=0644 backup=true

    #- name: Download Q
      #get_url: url=https://raw.github.com/harelba/q/1.3.0/q dest=/home/vagrant/tools/q mode=0755 owner=vagrant group=vagrant
    #- name: Download TextQL
      #shell: sudo GOPATH=/home/vagrant/.go go get github.com/dinedal/textql
