---
- hosts: all 
  roles:
    - { role: common, sudo: yes }
    - { role: docker, sudo: yes }
    - { role: python, sudo: yes }
    - { role: r, sudo: yes }
    - { role: julia, sudo: yes }
    - { role: javascript, sudo: yes }
    #- { role: nbviewer, sudo: yes }
    - { role: vowpal, sudo: yes }
    - { role: weka, sudo: yes }
    - { role: spark, sudo: yes }
    - { role: commandline, sudo: yes }
